/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.fileflow.controller;import cn.zhuatech.fileflow.service.FileBatchPlanService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                   */
@RestController @RequestMapping("/api/fileflow") @CrossOrigin public class FileBatchPlanController{private final FileBatchPlanService s;/**
                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                           */
public FileBatchPlanController(FileBatchPlanService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                            */
@PostMapping("/plan") FileBatchPlanService.Result plan(@Valid @RequestBody FileBatchPlanService.Request r){return s.plan(r);}}
