/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.fileflow;import cn.zhuatech.fileflow.service.FileBatchPlanService;import org.junit.jupiter.api.Test;import java.util.*;import static org.junit.jupiter.api.Assertions.*;/**
                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                             */
class FileBatchPlanServiceTests{private final FileBatchPlanService s=new FileBatchPlanService();/**
                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                             */
@Test void plansPdfConversionBatches(){var r=s.plan(new FileBatchPlanService.Request("CONVERT_PDF",List.of(new FileBatchPlanService.FileMeta("a.docx","docx",60),new FileBatchPlanService.FileMeta("b.png","png",50)),100,20));assertEquals("READY",r.status());assertEquals(2,r.batchCount());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@Test void reviewsUnsupportedSpreadsheet(){var r=s.plan(new FileBatchPlanService.Request("CONVERT_PDF",List.of(new FileBatchPlanService.FileMeta("a.xlsx","xlsx",5),new FileBatchPlanService.FileMeta("b.docx","docx",5)),100,20));assertEquals("REVIEW",r.status());}}
